### PR TITLE
Add getPriceWithConditions and getPriceSumWithConditions in ItemColletion

### LINKED ISSUE #33: Subtotal after apply cartcondition
How do I get subtotal per item after apply cartcondition using Cart::getContent()?

### PR DESCRIPTION
**Pull request by SimoTod**
In my cart I need to show price per row in which conditions are already applied.
Each ItemCollection has a method getPriceWithConditions and getPriceSumWithConditions.
Cart use getPriceSumWithConditions to calculate subtotal. 
These commits resolve #33.

### CODE REVIEW

**Comment by darryldecode** [comment]
Hello @SimoTod ,

Going to review this PR. Thank you for your time :)

**Comment by it-can** [comment]
+1

**Comment by darryldecode** [comment]
hello @SimoTod , can you as well update the docs for this and make another PR? Thanks!:)

**Comment by SimoTod** [comment]
Hi @darryldecode, sure. I will send you the PR as soon as possible.

**Pull request merged**
