### PR TITLE
Update Cart.php

### PR DESCRIPTION
**Pull request by onyanov**

### CODE REVIEW

**Comment by darryldecode** [comment]
Hi @onyanov, thank you for your time. I guess you miss this in docs:

```
$cartCollection = Cart::getContent();
$cartCollection->count();
```

**Comment by onyanov** [comment]
Hi @darryldecode. This was doesn't use quantity of each products.

**Comment by darryldecode** [comment]
@onyanov, yes you're right. But it might be confusing with getting total items in the cart vs getting total items(with respect to their quantity) in the cart? Or perhaps maybe there's a better method name for that?

**Comment by darryldecode** [comment]
Hi @onyanov, can you do a rebase on this PR before I can do a merge on this. Thanks!

**Pull request closed without merging**
