### PR TITLE
Ability to associate Models to a cart item.

### LINKED ISSUE #92: Ability to associate a product model to an item
I was wondering, would it be nice if we can associate a model for the item? It wouldn't necessary to make an eloquent query again if the product entity could access through our Cart instance?
Something like this:

```php
$item = Cart::add(123, 'Product Sample', 100.99, 2, $attributes)->associate(Product::class);

// This will return an App\Product instance
$product = $item->model;

// With this, we may perform accessing its relationship to other models and other model stuff
$product->category->name;

```

Looking forward to seeing this on the project.

### PR DESCRIPTION
**Pull request by alhaji-aki**
Fixes #92 Well I was able to do something regarding this issue. I hope it is accepted. Please this is my first ever pull request so I pray it works and is accepted. Thanks for this package.

### CODE REVIEW

**Comment by alhaji-aki** [comment]
> can you as well update the docs(readme)? I am still reviewing this PR. Thanks for your effort.

I did check here [Associating Models](https://github.com/alhaji-aki/laravelshoppingcart#associating-models)

**Comment by darryldecode** [comment]
Hi @alhaji-aki sorry for late review, very busy :( I finally had the time. If you have some spare time, can you check the 1 failing test before I merge. I already resolved the conflicts. Thanks!

image

**Comment by alhaji-aki** [comment]
Ok will do so... later in the day...

**Comment by darryldecode** [comment]
@alhaji-aki thank you 👍

**Pull request merged**
