### PR TITLE
Update laravel 6 to semantic versioning scheme

### PR DESCRIPTION
**Pull request by lloricode**
https://laravel.com/docs/6.x/releases#versioning-scheme

### CODE REVIEW

**Comment by lloricode** [comment]
as of now, it can not install with latest laravel 6.2.0

so downgrading is solution, BUT this should must compatible of current major version of laravel

**Comment by mohamedsabil83** [comment]
Please, merge this PR to compatible with Laravel6 semver scheme.

**Comment by luecano** [comment]
Since this package supports all versions of Laravel 5 from 5.0 up to 5.8 just change composer.json to:

    "illuminate/support": "^5|^6",
    "illuminate/validation": "^5|^6",
    "illuminate/translation": "^5|^6"

or:

    "illuminate/support": "^5.0|^6.0",
    "illuminate/validation": "^5.0|^6.0",
    "illuminate/translation": "^5.0|^6.0"

btw 6.4.0 was released a couple of days ago

**Comment by darryldecode** [comment]
Thank you. There are currently PHP version tests failing because of 5.6 support tests. Might have to move to php 7+ soon and drop 5.6. Thanks for the PR.

**Pull request merged**
