### PR TITLE
Support Laravel 10

### PR DESCRIPTION
**Pull request by ultrono**

### CODE REVIEW

**Comment by Mo7sin** [comment]
I'm not sure if this package is maintained anymore!

**Comment by ultrono** [comment]
Ah,l if it isn't I'll probably make a quick fork, as from the code I can;t see anything that would cause issues with Laravel 9.

**Comment by ultrono** [comment]
Right, it does appear this repository is dead. 

I've created a fork at https://github.com/ultrono/laravelshoppingcart-1

Enhancements include Github actions, fix of tests and Laravel 10 support. Installation via `composer require ultrono/laravelshoppingcart-1`

**Comment by Dibbyo456** [comment]
Thank you 🙏

**Comment by wilkker** [comment]
> Obrigado🙏

how did you do ?

**Comment by wilkker** [comment]
> > Obrigado🙏
> 
> how did you do ?

thanks, it works now

**Comment by ultrono** [comment]
Nice 👍

**Pull request merged**
