### PR TITLE
New needed methods

### PR DESCRIPTION
**Pull request by aalyusuf**
Cart::getSubTotalWithoutConditions();
To calculate Cart subtotal before conditions are applied. 
Also $item->getConditions(); to get item conditions.

### CODE REVIEW

**Comment by darryldecode** [comment]
@ebisbe @SimoTod any thoughts?

**Comment by ebisbe** [comment]
@darryldecode  I have this method in my fork. I'll make a PR and we can review it there.

**Comment by ebisbe** [comment]
I have the tests also already done. I can PR them once this is finally accepted.

https://github.com/ebisbe/laravelshoppingcart/commit/d15843bb65cd6878b13fe1421b11e6a9b43956cd

@aalyusuf Can you create 2 tests for the getConditons() method? One for empty conditions and the other with some conditions applied.

**Comment by aalyusuf** [comment]
@ebisbe Alright, done

**Comment by ebisbe** [comment]
thanks @aalyusuf!  For me it's fine @darryldecode

**Comment by darryldecode** [comment]
@ebisbe  @aalyusuf thanks guys! 👍

**Pull request merged**
